### PR TITLE
Add sensible chunk names

### PR DESCRIPTION
**Pull request by RCinbo**

### CODE REVIEW

**Comment by wlangera** [comment]
I cannot knit this due to the following issue:
```
Error:
! [conflicted] combine found in 2 packages.
Either pick the one you want with `::`:
• dplyr::combine
• gridExtra::combine
Or declare a preference with `conflicted::conflicts_prefer()`:
• `conflicted::conflicts_prefer(dplyr::combine)`
• `conflicted::conflicts_prefer(gridExtra::combine)`
Backtrace:
  1. brms::brm(...)
 19. conflicted (local) `<fn>`()
```

Is it necessary to load package gridExtra?
You do not seem to use it and if it will be used it will be rare so maybe use `gridExtra::grid.arrange()` directly.

**Comment by RCinbo** [comment]
It's only used once in the mcmc script. Ik van be removed.
Thanks!

**Comment by wlangera** [comment]
@RCinbo I have proposed some minor adjustmetns in PR #6

**Comment by wlangera** [comment]
Finally, will we use theta as parameter for the poisson models or lambda? Now we use both

**Comment by ToonVanDaele** [comment]
> Finally, will we use theta as parameter for the poisson models or lambda? Now we use both

In R it's called lambda.   rpois(n, lambda)

**Comment by RCinbo** [comment]
Theta was replaced by lambda in the main  #https://github.com/inbo/bayesian-workshop-2023/commit/fead74dbe3625289eb13cfbc708e4694802e3382

**Pull request merged**
